version: 2
updates:
    # Bump eco-goinfra dependecy on a daily basis
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/openshift-kni/eco-goinfra"
    commit-message:
      prefix: "[Bump eco-goinfra] "
    labels:
      - "dependencies"

    # Bump all dependencies once a month
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Bump dependencies] "
    labels:
      - "dependencies"
