run:
  go: "1.24"
  timeout: 15m
#  modules-download-mode: readonly

linters-settings:
  misspell:
    ignore-words:
      - "nto"
  revive:
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: increment-decrement
      - name: exported
        arguments:
          - disableStutteringCheck
  depguard:
    rules:
      main:
        deny:
        - pkg: "github.com/onsi**"
        allow:
        - "github.com/onsi/ginkgo/v2/types"
        - "k8s.io/apimachinery"
        - "k8s.io/api"
        - "k8s.io/kubelet"
        - "k8s.io/utils"
        - "k8s.io/client-go"
        - "github.com/kelseyhightower"
        - "github.com/Juniper/go-netconf"
        - "github.com/openshift"
        - "github.com/nmstate/kubernetes-nmstate"
        - "github.com/hashicorp/go-version"
        - "github.com/cavaliergopher/grab/v3"
        - "github.com/k8snetworkplumbingwg"
        - "github.com/metallb/metallb-operator"
        - "github.com/metal3-io/baremetal-operator"
        - "github.com/operator-framework/operator-lifecycle-manager"
        - "github.com/grafana-operator/grafana-operator"
        - "github.com/NVIDIA/gpu-operator"
        - "github.com/operator-framework/api"
        - "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
        - "github.com/vmware-tanzu/velero/pkg/generated/clientset/versioned/scheme"
        - "github.com/golang/glog"
        - "github.com/povsister/scp"
        - "maistra.io/api"
        - "open-cluster-management.io/governance-policy-propagator/api"
        - "open-cluster-management.io/config-policy-controller/api"
        - "open-cluster-management.io/multicloud-operators-subscription/pkg/apis"
        - "sigs.k8s.io/controller-runtime"
        - $gostd
        - "github.com/stretchr/testify"
        - "github.com/stmcginnis/gofish"
        - "github.com/BurntSushi/toml"
        - "github.com/containers/image/v5/pkg/sysregistriesv2"
        - "gopkg.in/yaml.v2"
        - "gopkg.in/yaml.v3"
        - "gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/types"
        - "golang.org/x/crypto/ssh"
        - "github.com/klauspost/compress/zstd"
        - "github.com/rh-ecosystem-edge/eco-gotests"
        - "github.com/rh-ecosystem-edge/eco-goinfra"
  wsl:
    strict-append: false
  gofmt:
    simplify: true
  funlen:
    lines: 90
    statements: 40
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/gomega
      - github.com/onsi/ginkgo/v2
      - github.com/rh-ecosystem-edge/eco-gotests/tests/internal/inittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/cnf/core/network/internal/netinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/cnf/ran/internal/raninittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/assisted/ztp/internal/ztpinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/ipsec/internal/ipsecinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/ran-du/internal/randuinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/internal/systemtestsinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/spk/internal/spkinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/vcore/internal/vcoreinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/lca/imagebasedupgrade/cnf/internal/cnfinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/hw-accel/kmm/internal/kmminittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/rhwa/internal/rhwainittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/rdscore/internal/rdscoreinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/lca/imagebasedupgrade/mgmt/internal/mgmtinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/accel/internal/accelinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/lca/imagebasedinstall/mgmt/internal/mgmtinittools
      - github.com/rh-ecosystem-edge/eco-gotests/tests/system-tests/diskencryption/internal/diskencryptioninittools
    # https://staticcheck.io/docs/options#checks
    checks:
      - all
      - ST1001

linters:
  disable:
    - ireturn
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - varnamelen
    - wsl
    - nlreturn

output:
  formats:
    - format: colored-line-number
issues:
  exclude-dirs-use-default: true
  exclude:
    - "can't run linter goanalysis_metalinter: inspect: failed to load"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  include:
    - EXC0002 # disable excluding of issues about comments from golint
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    #- # Exclude some linters from running on tests files.

    - path: 'tests/internal/inittools'
      linters:
        - gochecknoinits
    - path: 'tests/accel/internal/accelinittools'
      linters:
        - gochecknoinits
    - path: 'tests/cnf/core/network/internal/netinittools'
      linters:
        - gochecknoinits
    - path: 'tests/cnf/ran/internal/raninittools'
      linters:
        - gochecknoinits
    - path: 'tests/assisted/ztp/internal/ztpinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/ipsec/internal/ipsecinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/ran-du/internal/randuinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/rdscore/internal/rdscoreinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/internal/systemtestsinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/spk/internal/spkinittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/vcore/internal/vcoreinittools'
      linters:
        - gochecknoinits
    - path: 'tests/lca/imagebasedupgrade/cnf/internal/cnfinittools'
      linters:
        - gochecknoinits
    - path: 'tests/hw-accel/kmm/internal/kmminittools'
      linters:
        - gochecknoinits
    - path: 'tests/rhwa/internal/rhwainittools'
      linters:
        - gochecknoinits
    - path: 'tests/system-tests/diskencryption/internal/diskencryptioninittools'
      linters:
        - gochecknoinits
    - path: 'tests/lca/imagebasedupgrade/mgmt/internal/mgmtinittools'
      linters:
        - gochecknoinits
    - path: 'tests/lca/imagebasedinstall/mgmt/internal/mgmtinittools'
      linters:
        - gochecknoinits
    - path: "tests/internal/inittools"
      linters:
        - depguard
    - path: 'tests/internal/reporter'
      linters:
        - depguard
    - path: 'tests/system-tests/internal/ocpcli'
      linters:
        - depguard
    - path: "tests/.*/tests/.*"
      linters:
        - depguard
    - path: "tests/.*/.*suite_test.go"
      linters:
        - depguard
    - path: "tests/system-tests/rdscore/internal/.*"
      linters:
        - depguard
    - path: "tests/system-tests/spk/internal/.*"
      linters:
        - depguard
    - path: "tests/system-tests/vcore/internal/.*"
      linters:
        - depguard
    - path: "tests/lca/imagebasedupgrade/cnf/internal/validations"
      linters:
        - depguard
