package mgmtparams

const (
	// Label represents mgmt label that can be used for test cases selection.
	Label = "mgmt"

	// IBIONamespace is the namespace where the image-based-install-operator runs.
	IBIONamespace = "multicluster-engine"

	// MGMTLogLevel custom loglevel for the mgmt testing verbose mode.
	MGMTLogLevel = 50

	// CaBundleString is the CA bundle string.
	CaBundleString = `-----BEGIN CERTIFICATE-----
MIIEBTCCAu2gAwIBAgIUKp897WUzzjMtZ2YQs7JTCvwLy1gwDQYJKoZIhvcNAQEL
BQAwgZExCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOQzEQMA4GA1UEBwwHUmFsZWln
aDETMBEGA1UECgwKUmVkSGF0IExURDELMAkGA1UECwwCUUUxGTAXBgNVBAMMEHFl
Ym94LnJlZGhhdC5jb20xJjAkBgkqhkiG9w0BCQEWF29ob2NobWFuLWFsbEByZWRo
YXQuY29tMB4XDTI0MTExOTE0MzY0N1oXDTI0MTIxOTE0MzY0N1owgZExCzAJBgNV
BAYTAlVTMQswCQYDVQQIDAJOQzEQMA4GA1UEBwwHUmFsZWlnaDETMBEGA1UECgwK
UmVkSGF0IExURDELMAkGA1UECwwCUUUxGTAXBgNVBAMMEHFlYm94LnJlZGhhdC5j
b20xJjAkBgkqhkiG9w0BCQEWF29ob2NobWFuLWFsbEByZWRoYXQuY29tMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxMHan2/lttpHFfw95d8prUYGuRXH
TTrbsWjKKqBEADgw/v/9T1/2LWBJpyW210EZpoyjhBSw7We5EqQAFenPdvBNQefa
qx/8feVZpyTux+pbJomyppx4tzwS1Bgn0Myn9mNBqFylEQH1TIIwhkeBcYsLis9/
9ECBgDE8haFRxpue8psEkWc5zouuFewejvjMpjIWNpQU337tb7LD945/oWbwo1fn
ZIl19O5aryrY7fA+NAczWm83oIcMt/Sp/Cg1ZfOXszgHFF1cbQrXWFzRZAgWAxTb
swpcqbyIHRtO+mle5IOnKjLj9ikuBrkhN6wybLD01VybrlLcESuGife0hwIDAQAB
o1MwUTAdBgNVHQ4EFgQUA247p0jVYog+OcD12/FGGzVQ0VswHwYDVR0jBBgwFoAU
A247p0jVYog+OcD12/FGGzVQ0VswDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAXik+/xFp/jGRDpFGgQwGJd7hbQ5WFuNt+5mGns9/Ws9fsGbbdlxc
jsM5YJoWb0sth2ovv+/4UDshGEYEunLe/AQ/xkG+7/sA0R86joUfNbdIm4AzgOC3
J3eaEmy777tsC71aMS/W7jEdwftdcRn/UHS+6oG69hpNUM3mU9EUYpeff8RbspY7
2nLwA5XqGknKE2MZrD3fSWWqIYiAqXze1lfLGIud+apQX9vryjefE9xXWXMd8mrZ
VJ/qsrFU7O5ktfvJ50DkIHLYCeTghzI0y1mTwfHF/g1N7dsIGmaL74Xp1akYPLmT
EBaAqEqwwGkygraipfs5BJSxtozhelqjpQ==
-----END CERTIFICATE-----`
)
