# Use the official RAPIDast image as the base
FROM quay.io/redhatproductsecurity/rapidast:2.8.0


# Set working directory to the RAPIDast installation
WORKDIR /opt/rapidast

COPY ./config/rapidastConfig.yaml ./config/
