name: Build Docker Image - CI (arm)

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      uses: redhat-actions/buildah-build@v2
      with:
        image: eco-gotests
        tags: ${{ github.event_name == 'push' && 'arm-latest' || github.ref_name }}
        containerfiles: |
          ./Dockerfile-arm

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: eco-gotests
        tags: ${{ github.event_name == 'push' && 'arm-latest' || github.ref_name }}
        registry: quay.io/ocp-edge-qe
        username: ocp-edge-qe+ocp_edge_qe_robot
        password: ${{ secrets.OCP_EDGE_QE_QUAY }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
